auction_analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: auction_analytics
      host: localhost
      port: 8123
      user: default
      password: ''
      secure: False